/* Rendering smoke tests in a minimal DOM stub, NOT a browser/E2E test. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
function setup(){
  const elements=new Map();
  function element(id){return {id,value:'',innerHTML:'',textContent:'',hidden:false,checked:false,disabled:false,dataset:{},events:{},classList:{toggle(){}},setAttribute(){},removeAttribute(){},addEventListener(name,fn){this.events[name]=fn;}};}
  for(const match of html.matchAll(/\bid="([^"]+)"/g)){assert.ok(!elements.has(match[1]),'duplicate HTML ID');elements.set(match[1],element(match[1]));}
  const tabs=Array.from(html.matchAll(/data-tab="([^"]+)"/g),m=>Object.assign(element('tab-'+m[1]),{dataset:{tab:m[1]}}));
  for(const [id,v] of Object.entries({temperature:'1','prompt':'The capital of Japan is called','attn-layer':'0','attn-head':'mean','attn-scale':'raw'}))elements.get(id).value=v;
  const document={getElementById(id){assert.ok(elements.has(id),'Unknown HTML ID '+id);return elements.get(id);},querySelectorAll(q){return q==='#navigation button'?tabs:[];},body:element('body')};
  const context=vm.createContext({document,console,Map,URL,Blob,setTimeout,clearTimeout,fetch:()=>{throw Error('Unexpected fetch');}});
  vm.runInContext(fs.readFileSync(path.join(root,'static/math.js'),'utf8'),context);
  vm.runInContext(fs.readFileSync(path.join(root,'static/app.js'),'utf8'),context);
  return {context,elements,run:s=>vm.runInContext(s,context)};
}
test('startup wires every control to real HTML IDs',()=>{const {elements}=setup();assert.equal(elements.get('sampling').hidden,false);assert.equal(elements.get('verification').hidden,true);for(const id of ['predict','inspect','generate','compare','intervene','verify','probe-fit'])assert.equal(typeof elements.get(id).events.click,'function');});
test('navigation changes panel and bounds',()=>{const {run,elements}=setup();run('showTab(8)');assert.equal(elements.get('verification').hidden,false);assert.equal(elements.get('next').disabled,true);run('showTab(-5)');assert.equal(elements.get('previous').disabled,true);});
test('distribution and temperature render without server rerun',()=>{const {run,elements}=setup();run(`state.prediction={prompt:'<script>',run_id:'test',logits:[3,2,1],vocab_size:3};state.names.set(0,'<img src=x>');renderDistribution();`);assert.ok(elements.get('distribution').innerHTML.includes('&lt;img'));assert.ok(!elements.get('distribution').innerHTML.includes('<script>'));elements.get('temperature').value='0';run('renderDistribution()');assert.equal(elements.get('temperature-value').textContent,'0.00');});
test('stale prompt warning retains provenance',()=>{const {run,elements}=setup();run(`state.records.push({prompt:'old prompt'});stale();`);assert.equal(elements.get('stale').hidden,false);});
test('attention raw and maximum envelope render with logarithmic profile',()=>{const {run,elements}=setup();run(`state.attention={prompt:'a b',run_id:'test',tokens:[{position:0,text:'a'},{position:1,text:'b'}],attentions:[[[[1,0],[.9,.1]],[[1,0],[.1,.9]]]],n_layers:1};renderAttention();`);assert.ok(elements.get('attention-result').innerHTML.includes('Mean of heads'));elements.get('attn-head').value='max';elements.get('attn-scale').value='ratio';run('renderAttention()');assert.ok(elements.get('attention-result').innerHTML.includes('not a distribution'));assert.ok(elements.get('sink-profile').innerHTML.includes('logarithmic'));});
test('single-position attention profile is explicit about overlap',()=>{const {run,elements}=setup();run(`renderProfile([{layer:1,first:1,self:1,other:null}],1,false)`);assert.ok(elements.get('sink-profile').innerHTML.includes('lines coincide'));});
test('real-measurement renderers accept structured results',()=>{const {run,elements}=setup();run(`const v={shape:[2],l2_norm:1,values:[1,0]};const d={run_id:'t',prompt:'a b',settings:{},query_head:1,shared_kv_head:1,head_dim:2,scale_divisor:Math.sqrt(2),vectors:{incoming:v},checks:[],attention_row:[],q_coordinate_0_projection:{},unembedding:{target_id:1,target_text:'b',dot_product:1,model_logit:1,cosine:1,probability_T1:.5,raw_final_state:v,normalized_final_state:v,weight_row:v,dot_terms:v}};for(const k of ['query_before_rope','query_after_rope','keys_before_rope','keys_after_rope','values','rope_cos','rope_sin','weighted_values','head_output','projected_position_contributions','head_residual_write'])d[k]=v;renderInspection(d);`);assert.ok(elements.get('inspection').innerHTML.includes('Full-input projection'));});
test('numeric arrays receive honest visual summaries and retain exact values',()=>{const {run}=setup();const vector=run(`vector('hidden_state',{shape:[4],l2_norm:2,values:[-1,0,.5,2]})`);assert.ok(vector.includes('Coordinate profile'));assert.ok(vector.includes('Value distribution'));assert.ok(vector.includes('Exact numeric values'));assert.ok(vector.includes('not necessarily semantically related'));const matrix=run(`numericView([[1,-1],[.5,0]])`);assert.ok(matrix.includes('Matrix heatmap'));assert.ok(matrix.includes('group mean'));});
test('learner-facing definitions and seed explanation are present',()=>{assert.ok(html.includes('Quick glossary'));assert.ok(html.includes('pseudorandom number generator'));assert.ok(html.includes('does <strong>not</strong> change the prompt'));assert.ok(html.includes('Analyze next-token distribution'));});
test('generation render escapes text and retains actual settings',()=>{const {run,elements}=setup();run(`renderGeneration({prompt:'A',run_id:'t',settings:{temperature:.3},forward_passes:1,unique_outputs:1,results:[{seed:42,generated_text:'<script>',full_text:'A<script>',seconds:1,stop_reason:'token_budget',steps:[]}]});`);assert.ok(!elements.get('generation-result').innerHTML.includes('<script>'));assert.ok(elements.get('generation-result').innerHTML.includes('0.3'));});
test('remaining result renderers render without undefined fields',()=>{const {run,elements}=setup();run(`const z={id:1,text:'b',model_probability:.5};renderIntervention({prompt:'a',run_id:'t',settings:{},target_text:'a',contrast_text:'b',baseline:{target_probability:.2,logit_difference:1},checks:[],rows:[{head:1,sink_share:.5,new_top:[z],top1_changed:false,target_probability:.4,delta_probability_pp:20,target_rank:1,tv:.2,js_nats:.01,delta_logit_difference:.1}],definition:'TV',forward_passes:2});renderLenses({run_id:'t',prompt:'a',target_id:1,target_text:'b',checks:[],stages:[{label:'raw',vector_norm:1,top:[z],target_rank:1,target_probability:.5,metrics_to_final:{kl_base_to_changed_nats:0},probe:null}]});renderComparison({run_id:'t',prompt:'a',settings:{prompt_b:'b'},tokens:[{position:0,id:1,text:'a'}],tokens_b:[{position:0,id:2,text:'b'}],metrics:{tv:0,js_nats:0},warning:'Separate axes',candidates:[],layers:[],last_row_a:[1],last_row_b:[1]});`);for(const id of ['intervention-result','lenses-result','comparison-result'])assert.ok(!elements.get(id).innerHTML.includes('undefined'),id);});
